In [15]:
import pandas as pd

In [21]:
clinic_csv = "/vol/biomedic3/bglocker/brain/oasis3/meta/ADRC_clinical_data.csv"
mr_csv = "/vol/biomedic3/bglocker/brain/oasis3/meta/MR_sessions.csv"

In [22]:
# ADRC clinical data
clinic = pd.read_csv(clinic_csv)
clinic
clinic[clinic["cdr"] == 3]

,ADRC_ADRCCLINICALDATA ID,Subject,Date,Age,mmse,ageAtEntry,cdr,commun,dx1,dx2,...,apoe,sumbox,acsparnt,height,weight,primStudy,acsStudy,Subject.1,Race,Ethnicity
158,OAS30029_ClinicalData_d1792,OAS30029,NaN,NaN,10.0,72.369610,3.0,2.0,AD dem Language dysf after,AD dem visuospatial- prior,...,34.0,16.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05118,Caucasian,Non-Hispanic
1466,OAS30282_ClinicalData_d1104,OAS30282,NaN,NaN,12.0,82.395620,3.0,2.0,Dementia/PD- primary,Active PD idiopathic,...,23.0,15.0,NaN,NaN,89.0,NaN,NaN,CENTRAL_S05345,African American,Non-Hispanic
2669,OAS30521_ClinicalData_d1579,OAS30521,NaN,NaN,1.0,70.017800,3.0,3.0,AD Dementia,Remote Mood disorder,...,34.0,17.0,NaN,NaN,142.0,NaN,NaN,CENTRAL_S05554,Caucasian,Non-Hispanic
2832,OAS30554_ClinicalData_d1909,OAS30554,NaN,NaN,6.0,74.012320,3.0,2.0,AD Dementia,Active Med-induced Cog Dys,...,34.0,16.0,NaN,63.0,100.0,NaN,NaN,CENTRAL_S05583,Caucasian,Non-Hispanic
2966,OAS30575_ClinicalData_d0956,OAS30575,NaN,NaN,NaN,65.177280,3.0,3.0,DLBD- primary,.,...,33.0,17.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05601,Caucasian,Non-Hispanic
3179,OAS30616_ClinicalData_d0513,OAS30616,NaN,NaN,0.0,76.265570,3.0,3.0,AD dem w/oth (list B) contribut,DLBD- secondary,...,34.0,18.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05639,Caucasian,Non-Hispanic
3321,OAS30654_ClinicalData_d1689,OAS30654,NaN,NaN,2.0,83.074610,3.0,3.0,AD Dementia,.,...,34.0,18.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05670,Caucasian,Non-Hispanic
5022,OAS30948_ClinicalData_d0826,OAS30948,NaN,NaN,9.0,77.932920,3.0,2.0,AD Dementia,.,...,34.0,15.0,NaN,62.0,88.0,NaN,NaN,CENTRAL_S05930,Caucasian,Non-Hispanic
5304,OAS31008_ClinicalData_d1487,OAS31008,NaN,NaN,0.0,86.332650,3.0,3.0,AD Dementia,.,...,34.0,18.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05986,African American,Non-Hispanic
5394,OAS31030_ClinicalData_d1101,OAS31030,NaN,NaN,14.0,78.193016,3.0,2.0,AD Dementia,AD dem w/depresss- not contribut,...,34.0,16.0,NaN,67.0,150.0,NaN,NaN,CENTRAL_S06006,Caucasian,Non-Hispanic
6090,OAS31152_ClinicalData_d1100,OAS31152,NaN,NaN,NaN,70.483230,3.0,3.0,AD dem Language dysf after,AD dem w/oth (list B) contribut,...,24.0,18.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S06116,Caucasian,Non-Hispanic
6204,OAS31169_ClinicalData_d4098,OAS31169,NaN,NaN,NaN,62.965090,3.0,3.0,AD Dementia,.,...,34.0,18.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S06133,Caucasian,Non-Hispanic

In [23]:
# MR session data
mr = pd.read_csv(mr_csv)
mr
mr[mr["Subject"]== "OAS30948"]

,MR ID,Date,Subject,Age,Scanner,Scans,FreeSurfers,PUPs,sex,Diagnosis,M/F,Hand,Education,Race,Ethnicity
1745,OAS30948_MR_d0076,NaN,OAS30948,78.0,3.0T,"angio(1), asl(1), bold(2), dwi(1), fieldmap(3)...",1.0,NaN,NaN,NaN,F,R,12.0,Caucasian,Non-Hispanic

In [5]:
mr[mr["Subject"]=="OAS30040"]

,MR ID,Date,Subject,Age,Scanner,Scans,FreeSurfers,PUPs,sex,Diagnosis,M/F,Hand,Education,Race,Ethnicity
93,OAS30040_MR_d2899,NaN,OAS30040,75.0,1.5T,"T1w(3), T2w(2)",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
94,OAS30040_MR_d4230,NaN,OAS30040,79.0,3.0T,"bold(2), dwi(1), minIP(1), swi(1), T1w(2), T2s...",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
95,OAS30040_MR_d5108,NaN,OAS30040,81.0,3.0T,"bold(2), T1w(1), T2w(2)",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic

# Matching command line instruction:

Instruction: python oasis_data_matchup.py --adrc ADRC_clinical_data.csv --sessions MR_sessions.csv --output_name test_matching_365_before.csv --lower_bound 180 --upper_bound 180

In [6]:
# matching data table generated with instruction above
match = "./test_matching/test_matching_365_b_365_a.csv"
csv_test = pd.read_csv(match)
csv_test.describe()

,Unnamed: 0,Date,Age,mmse,ageAtEntry,cdr,commun,homehobb,judgment,memory,...,acsStudy,Day,Date_MR,Age_MR,FreeSurfers_MR,PUPs_MR,sex_MR,Diagnosis_MR,Education_MR,Day_MR
count,2993.000000,0.0,0.0,2990.000000,2993.000000,2993.000000,2991.000000,2991.000000,2991.000000,2991.000000,...,0.0,2993.000000,0.0,2948.000000,2814.0,0.0,0.0,0.0,2979.000000,2993.000000
mean,3062.617775,NaN,NaN,28.177258,68.587363,0.167892,0.121364,0.145771,0.169843,0.187228,...,NaN,1444.876712,NaN,72.005088,1.0,NaN,NaN,NaN,15.670695,1435.923154
std,1795.867709,NaN,NaN,2.789363,8.703981,0.332047,0.333194,0.372528,0.370853,0.379734,...,NaN,1633.513064,NaN,8.799523,0.0,NaN,NaN,NaN,2.714038,1631.554918
min,0.000000,NaN,NaN,0.000000,42.469540,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,0.000000,NaN,42.000000,1.0,NaN,NaN,NaN,7.000000,0.000000
25%,1474.000000,NaN,NaN,28.000000,64.076660,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,0.000000,NaN,67.000000,1.0,NaN,NaN,NaN,13.000000,109.000000
50%,3044.000000,NaN,NaN,29.000000,68.689940,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,896.000000,NaN,72.000000,1.0,NaN,NaN,NaN,16.000000,910.000000
75%,4635.000000,NaN,NaN,30.000000,74.012320,0.500000,0.000000,0.000000,0.000000,0.000000,...,NaN,2276.000000,NaN,78.000000,1.0,NaN,NaN,NaN,18.000000,2324.000000
max,6221.000000,NaN,NaN,30.000000,95.567420,3.000000,3.000000,3.000000,3.000000,3.000000,...,NaN,9938.000000,NaN,97.000000,1.0,NaN,NaN,NaN,29.000000,9874.000000

In [7]:
list(csv_test)

['Unnamed: 0',
 'ADRC_ADRCCLINICALDATA ID',
 'Subject',
 'Date',
 'Age',
 'mmse',
 'ageAtEntry',
 'cdr',
 'commun',
 'dx1',
 'dx2',
 'dx3',
 'dx4',
 'dx5',
 'homehobb',
 'judgment',
 'memory',
 'orient',
 'perscare',
 'apoe',
 'sumbox',
 'acsparnt',
 'height',
 'weight',
 'primStudy',
 'acsStudy',
 'Subject.1',
 'Race',
 'Ethnicity',
 'Day',
 'MR ID_MR',
 'Date_MR',
 'Subject_MR',
 'Age_MR',
 'Scanner_MR',
 'Scans_MR',
 'FreeSurfers_MR',
 'PUPs_MR',
 'sex_MR',
 'Diagnosis_MR',
 'M/F_MR',
 'Hand_MR',
 'Education_MR',
 'Race_MR',
 'Ethnicity_MR',
 'Day_MR']

In [8]:
cols = ["ADRC_ADRCCLINICALDATA ID", "MR ID_MR", "Day_MR"]
csv_test[cols]

         ADRC_ADRCCLINICALDATA ID           MR ID_MR  Day_MR
0     OAS30001_ClinicalData_d0000  OAS30001_MR_d0129   129.0
1     OAS30001_ClinicalData_d0339  OAS30001_MR_d0129   129.0
2     OAS30001_ClinicalData_d0722  OAS30001_MR_d0757   757.0
3     OAS30001_ClinicalData_d1106  OAS30001_MR_d0757   757.0
4     OAS30001_ClinicalData_d2181  OAS30001_MR_d2430  2430.0
...                           ...                ...     ...
2988  OAS31170_ClinicalData_d2697  OAS31170_MR_d2410  2410.0
2989  OAS31171_ClinicalData_d0763  OAS31171_MR_d0752   752.0
2990  OAS31172_ClinicalData_d0406  OAS31172_MR_d0407   407.0
2991  OAS31172_ClinicalData_d1565  OAS31172_MR_d1717  1717.0
2992  OAS31172_ClinicalData_d1908  OAS31172_MR_d1717  1717.0

[2993 rows x 3 columns]

In [9]:
csv_test[csv_test["cdr"] > 1 ]

,Unnamed: 0,ADRC_ADRCCLINICALDATA ID,Subject,Date,Age,mmse,ageAtEntry,cdr,commun,dx1,...,FreeSurfers_MR,PUPs_MR,sex_MR,Diagnosis_MR,M/F_MR,Hand_MR,Education_MR,Race_MR,Ethnicity_MR,Day_MR
260,495,OAS30098_ClinicalData_d0372,OAS30098,NaN,NaN,10.0,65.182755,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic,36.0
395,780,OAS30145_ClinicalData_d4492,OAS30145,NaN,NaN,15.0,68.714580,2.0,1.0,DLBD- primary,...,1.0,NaN,NaN,NaN,M,R,16.0,Caucasian,Non-Hispanic,4247.0
428,864,OAS30158_ClinicalData_d2559,OAS30158,NaN,NaN,16.0,72.668040,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,18.0,Caucasian,Non-Hispanic,2467.0
521,1055,OAS30194_ClinicalData_d9938,OAS30194,NaN,NaN,27.0,60.676250,2.0,2.0,AD dem w/oth (list B) contribut,...,NaN,NaN,NaN,NaN,M,R,18.0,Caucasian,Non-Hispanic,9874.0
630,1271,OAS30243_ClinicalData_d0000,OAS30243,NaN,NaN,13.0,50.261463,2.0,2.0,Frontotemporal demt. prim,...,1.0,NaN,NaN,NaN,F,R,12.0,Caucasian,Non-Hispanic,34.0
633,1275,OAS30244_ClinicalData_d1848,OAS30244,NaN,NaN,12.0,73.013010,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,12.0,Caucasian,Non-Hispanic,1526.0
713,1415,OAS30271_ClinicalData_d0000,OAS30271,NaN,NaN,12.0,66.050650,2.0,2.0,AD dem Language dysf after,...,1.0,NaN,NaN,NaN,M,R,18.0,Caucasian,Non-Hispanic,4.0
980,1938,OAS30373_ClinicalData_d1474,OAS30373,NaN,NaN,15.0,69.828890,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,M,R,18.0,Caucasian,Non-Hispanic,1211.0
1126,2291,OAS30440_ClinicalData_d0000,OAS30440,NaN,NaN,7.0,77.264885,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic,163.0
1560,3179,OAS30616_ClinicalData_d0513,OAS30616,NaN,NaN,0.0,76.265570,3.0,3.0,AD dem w/oth (list B) contribut,...,1.0,NaN,NaN,NaN,F,R,14.0,Caucasian,Non-Hispanic,199.0
1646,3360,OAS30661_ClinicalData_d0375,OAS30661,NaN,NaN,18.0,91.655030,2.0,2.0,AD dem Language dysf after,...,NaN,NaN,NaN,NaN,M,R,18.0,Caucasian,Non-Hispanic,57.0
1896,3905,OAS30753_ClinicalData_d0343,OAS30753,NaN,NaN,21.0,61.070000,2.0,2.0,"DLBD, primary",...,1.0,NaN,NaN,NaN,F,R,12.0,Caucasian,Non-Hispanic,35.0
1947,4005,OAS30773_ClinicalData_d0000,OAS30773,NaN,NaN,20.0,71.000000,2.0,2.0,AD Dementia,...,NaN,NaN,NaN,NaN,F,R,12.0,Caucasian,Non-Hispanic,44.0
2201,4564,OAS30865_ClinicalData_d0368,OAS30865,NaN,NaN,24.0,73.697464,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,12.0,African American,Non-Hispanic,109.0
2338,4818,OAS30911_ClinicalData_d0000,OAS30911,NaN,NaN,17.0,72.996574,2.0,2.0,DLBD- primary,...,1.0,NaN,NaN,NaN,M,R,14.0,Caucasian,Non-Hispanic,99.0
2527,5205,OAS30987_ClinicalData_d1288,OAS30987,NaN,NaN,15.0,65.587950,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,M,A,14.0,African American,Non-Hispanic,965.0
2545,5235,OAS30994_ClinicalData_d0420,OAS30994,NaN,NaN,20.0,68.298420,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,18.0,Caucasian,Non-Hispanic,70.0
2554,5249,OAS30999_ClinicalData_d0347,OAS30999,NaN,NaN,17.0,76.060234,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,F,R,11.0,African American,Non-Hispanic,153.0
2647,5409,OAS31033_ClinicalData_d0356,OAS31033,NaN,NaN,19.0,87.805610,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,M,R,12.0,African American,Non-Hispanic,2.0
2702,5542,OAS31054_ClinicalData_d2703,OAS31054,NaN,NaN,19.0,62.023273,2.0,2.0,AD Dementia,...,1.0,NaN,NaN,NaN,M,R,18.0,Caucasian,Non-Hispanic,2787.0
2903,6001,OAS31135_ClinicalData_d0776,OAS31135,NaN,NaN,18.0,65.311430,2.0,2.0,DLBD- primary,...,NaN,NaN,NaN,NaN,M,R,12.0,Caucasian,Non-Hispanic,498.0
2958,6127,OAS31156_ClinicalData_d0000,OAS31156,NaN,NaN,21.0,81.347020,2.0,2.0,Dementia/PD- primary,...,1.0,NaN,NaN,NaN,M,A,16.0,Caucasian,Non-Hispanic,1.0

In [10]:
csv_test[csv_test["Subject"] == "OAS30003"]

,Unnamed: 0,ADRC_ADRCCLINICALDATA ID,Subject,Date,Age,mmse,ageAtEntry,cdr,commun,dx1,...,FreeSurfers_MR,PUPs_MR,sex_MR,Diagnosis_MR,M/F_MR,Hand_MR,Education_MR,Race_MR,Ethnicity_MR,Day_MR
11,23,OAS30003_ClinicalData_d2630,OAS30003,NaN,NaN,29.0,58.77344,0.0,0.0,Cognitively normal,...,1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic,2682.0
12,24,OAS30003_ClinicalData_d2970,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,...,1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic,3320.0
13,25,OAS30003_ClinicalData_d3288,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,...,1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic,3320.0
14,26,OAS30003_ClinicalData_d3633,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,...,1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic,3731.0

- Unnamed:0 is the session number (so 0 is their first), so relates to ADRC...ID col.
- Then day MR is the MR sesion you should use

In [11]:
# See how the numbered column (i.e. pandas native numbering of rows) corresponds to unanmed:0 above
clinic[clinic["Subject"] == "OAS30003"]

,ADRC_ADRCCLINICALDATA ID,Subject,Date,Age,mmse,ageAtEntry,cdr,commun,dx1,dx2,...,apoe,sumbox,acsparnt,height,weight,primStudy,acsStudy,Subject.1,Race,Ethnicity
20,OAS30003_ClinicalData_d0000,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,.,...,33.0,0.0,NaN,NaN,159.0,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
21,OAS30003_ClinicalData_d1083,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,.,...,33.0,0.0,NaN,65.0,164.0,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
22,OAS30003_ClinicalData_d2228,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,.,...,33.0,0.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
23,OAS30003_ClinicalData_d2630,OAS30003,NaN,NaN,29.0,58.77344,0.0,0.0,Cognitively normal,.,...,33.0,0.0,NaN,NaN,NaN,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
24,OAS30003_ClinicalData_d2970,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,.,...,33.0,0.0,NaN,65.0,164.0,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
25,OAS30003_ClinicalData_d3288,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,.,...,33.0,0.0,NaN,65.0,162.0,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
26,OAS30003_ClinicalData_d3633,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,Remote B-12 Deficiency,...,33.0,0.0,NaN,67.0,160.0,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic
27,OAS30003_ClinicalData_d4165,OAS30003,NaN,NaN,30.0,58.77344,0.0,0.0,Cognitively normal,Remote B-12 Deficiency,...,33.0,0.0,NaN,65.0,166.0,NaN,NaN,CENTRAL_S05096,Caucasian,Non-Hispanic

In [12]:
# see how the dXXXX at the end of MRID corresponds to 'Day MR' in  CSV_test
mr[mr["Subject"] == "OAS30003"]

,MR ID,Date,Subject,Age,Scanner,Scans,FreeSurfers,PUPs,sex,Diagnosis,M/F,Hand,Education,Race,Ethnicity
8,OAS30003_MR_d0558,NaN,OAS30003,60.0,3.0T,"bold(3), T1w(2), T2w(2)",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
9,OAS30003_MR_d1631,NaN,OAS30003,63.0,3.0T,"asl(2), bold(2), dwi(2), FLAIR(1), GRE(2), min...",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
10,OAS30003_MR_d2669,NaN,OAS30003,66.0,3.0T,"asl(2), bold(2), dwi(2), fieldmap(3), GRE(2), ...",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
11,OAS30003_MR_d2682,NaN,OAS30003,66.0,3.0T,"angio(5), asl(1), dwi(1), fieldmap(3), FLAIR(1...",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
12,OAS30003_MR_d3320,NaN,OAS30003,NaN,NaN,"angio(1), T1w(1)",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic
13,OAS30003_MR_d3731,NaN,OAS30003,68.0,3.0T,"angio(1), asl(1), bold(2), dwi(2), fieldmap(3)...",1.0,NaN,NaN,NaN,F,R,16.0,Caucasian,Non-Hispanic

In [13]:
!pwd

/vol/bitbucket/wjb120/data/ukbb_mesh/oasis3